apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: workshop-kustomization
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./path/to/your/configuration
  prune: true
  sourceRef:
    kind: GitRepository
    name: workshop-repo
  validation: client